### ISSUE TITLE
.flat is not supported in Edge

### ISSUE THREAD

**Issue by sateffen** [kaoDev/react-virtual-grid#1]
Array.prototype.flat is not supported in Edge, so this line: https://github.com/kaoDev/react-virtual-grid/blob/e8464249654ffd00abdf61052b7aa0cc6108e6ee/src/App.tsx#L176 prevents the demo from working in Edge.

Based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat this is just a proposal, so it might not work for quite a long time.

Firefox ESR is not supported as well because of this method, because the currently active ESR version is FF@60, but the method was added in FF@62.

Cheers

**Comment by kaoDev** [comment]
hey thanks for testing and for this issue, it got already fixed a few seconds ago with commit 41b7309badbe20229862a41c63685abef35f65db
